services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD 
      - SEQ_USERNAME=
    ports:
      - "5341:5341"   
      - "8080:80" 
    volumes:
      - api-logs:/data/ElearnLogs
 
volumes:
  api-logs: